### ISSUE TITLE
Please push new version to rubygems

### ISSUE THREAD

**Issue by hxegon** [rwdaigle/heroku-log-parser#6]
Might be missing something, but gem install heroku-log-parser installs 0.2 (I'm using 2.4.1)

Just a little thing, but I'd appreciate it. I'm using this in a standalone ruby script with no Gemfile.

**Comment by rwdaigle** [comment]
Hi @hxegon. Funny story, I'm not the owner of the [gem on RubyGems](https://rubygems.org/gems/heroku-log-parser), ha! Looks like somebody else published my library for me - probably to scratch their own itch.

I've asked them to transfer to the gem ownership to me so I can manage it going forward. Stay tuned!

**Comment by rykov** [comment]
@rwdaigle The probability that the email I just received is not you is low, however, for full security, I want to confirm that your RubyGems username is **rwdaigle** before I do the transfer.

**Comment by rwdaigle** [comment]
@rykov Hi! Yes, that's me.

**Comment by rykov** [comment]
@rwdaigle Done! https://rubygems.org/gems/heroku-log-parser

**Comment by rwdaigle** [comment]
Thank you @rykov!

@hxegon the latest version has been uploaded: https://rubygems.org/gems/heroku-log-parser/versions/0.4.0
